version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - devops
  sonarqube:
    image: sonarqube:latest
    restart: always
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    volumes:
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_logs:/opt/sonarqube/logs'
    depends_on:
      - db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    networks:
      - devops
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      devops:
  nexus:
    image: sonatype/nexus3:latest
    restart: always
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - devops
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    volumes:
      - 'prometheus_data:/prometheus'
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - devops
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - 'grafana_data:/var/lib/grafana'
    networks:
      - devops
    depends_on:
      - prometheus
networks:
  devops:
      name: devops 
volumes:
  postgresql:
    driver: local
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_logs:
    driver: local
  mysql-data:
    driver: local
  nexus_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local