version: '3.7'
services:

  backend:
    image: krayaaccount/devopsazizkefi:back-latest
    restart: always
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - devops

networks:
  devops:
    external: true
